on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          cd PY
          python single_exp.py
          cd ..
      - name: Compile
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            latexmk -pdf DYNDSP.tex
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: NON.pdf
          asset_name: NON.pdf
          tag: latest
          overwrite: true
